data:
  data_dict: !expr here::here("data", "__data_dictionary.xlsx")
  gene_data: !expr here::here("data", "gene_data.xlsx")
  PCR:
    vasc_raw: !expr here::here("data", "PCR", "vasc_raw.xlsx")
  IHC:
    clearing_raw: !expr here::here("data", "IHC", "clearing_raw.xlsx")
