# Markdown flavor and line width
flavor = "quarto"

# Formatting style
[format]
line-width = 120
line-ending = "auto"
blank-lines = "collapse"  # Blankline handling. Options: "collapse", "preserve"
wrap = "reflow"

# External code formatters (opt-in)
[formatters]
r = "air"
python = "ruff"
js = "prettier"
javascript = "prettier"
typescript = "prettier"

[formatters.prettier]
args = ["--parser", "babel"]

[lint.rules]
missing-chunk-labels = false

# External code linters
[linters]
r = "jarl"
