```{r}
source("src/setup.R", echo = FALSE)
```

```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(ggplot2)
  library(emmeans)
  library(insight)
  library(gtools)
})
```

```{r}
dat <- mtcars |> 
  transmute(hp = hp, cyl = factor(paste0("cyl", cyl)), am = factor(paste0("am", am)))

mod <- glm(hp ~ am * cyl, family = Gamma(link = "log"), data = dat)
```

```{r}
make_interaction_boxplot <- function(mod, pred1, pred2, scale = c("link", "response"), adjust = "none", adjust_inter = "none") {
  
  label_pval <- function(p) {
    return(
      str_c(
        scales::label_pvalue()(p) |> str_remove(">") |> str_trim(), 
        gtools::stars.pval(p) |> str_replace(fixed("."), ""), 
        sep = " "
      )
    )
  }
  
  dat <- insight::get_data(mod)
  resp <- insight::find_response(mod)
  
  scale <- scale[[1]]
  
  ## Making sure the variables of interest are factors for emmeans
  dat <- dat |> mutate(across(c(any_of(c(pred1, pred2)) & where(\(c) !is.factor(c))), as.factor))
  
  max <- max(dat[[resp]])
  min <- min(dat[[resp]])
  amp <- abs(max - min)
  
  # -----------[ Contrasts ]----------- #
  
  specs <- paste0(" ~ ", pred1)
  if(!is.null(pred2)) specs <- paste0(specs, " | ", pred2)
  specs <- as.formula(specs)
  
  emmeans <- emmeans::emmeans(mod, specs = specs, type = "response", data = dat)
  
  # Scale = response -> compute contrasts on response scale
  if (tolower(scale) %in% c("response", "resp")) {
    emmeans <- emmeans::regrid(emmeans, transform = "response")
  }
  
  contrasts <- emmeans::contrast(emmeans, method = "pairwise", adjust = adjust, infer = TRUE) |> 
    as.data.frame() |> 
    rename(Contrast = contrast) |> 
    separate_wider_regex(cols = Contrast, patterns = c(X1 = ".*", " [- | /] ", X2 = ".*"), cols_remove = FALSE)
  
  p_data_contrasts <- (
    contrasts 
    |> group_by(across(any_of(c(pred2)))) 
    |> mutate(
      x1 = (match(.data[[pred2]], levels(dat[[pred2]])) - 1) * length(unique(dat[[pred1]])) + match(X1, levels(dat[[pred1]])),
      x2 = (match(.data[[pred2]], levels(dat[[pred2]])) - 1) * length(unique(dat[[pred1]])) + match(X2, levels(dat[[pred1]])),
      p.signif = label_pval(p_value)
    ) 
    |> arrange(x.diff := abs(x2 - x1)) 
    |> mutate(
      step = 1:n(),
      pos.x = (x2 + x1) * 0.5,
      pos.y = max + step * 0.1 * (max - min)
    ) 
    |> ungroup()
  )
  
  contrasts_interactions <- emmeans::contrast(emmeans, interaction = c("pairwise"), by = NULL, adjust = adjust_inter, infer = TRUE) |> 
    as.data.frame() |> 
    separate_wider_regex(cols = paste0(pred1, "_pairwise"), patterns = c(X1 = ".*", " [- | /] ", X2 = ".*"), cols_remove = FALSE) |> 
    separate_wider_regex(cols = paste0(pred2, "_pairwise"), patterns = c(F1 = ".*", " [- | /] ", F2 = ".*"), cols_remove = FALSE)
  
  p_data_interactions <- (
    contrasts_interactions
    |> mutate(
      x1 = 0.5 * ((match(F1, levels(dat[[pred2]])) - 1) * length(unique(dat[[pred1]])) + match(X1, levels(dat[[pred1]])) +
                    (match(F1, levels(dat[[pred2]])) - 1) * length(unique(dat[[pred1]])) + match(X2, levels(dat[[pred1]]))),
      x2 = 0.5 * ((match(F2, levels(dat[[pred2]])) - 1) * length(unique(dat[[pred1]])) + match(X1, levels(dat[[pred1]])) +
                    (match(F2, levels(dat[[pred2]])) - 1) * length(unique(dat[[pred1]])) + match(X2, levels(dat[[pred1]]))),
      p.signif = label_pval(p_value)
    ) 
    |> arrange(x.diff := abs(x2 - x1)) 
    |> mutate(
      step = 1:n() + choose(length(unique(dat[[pred1]])), 2),
      pos.x = (x2 + x1) * 0.5,
      pos.y = max + step * 0.1 * (max - min)
    )
  )
  
  # -----------[ Plot ]----------- #
  
  return(
    ggplot(dat, aes(x = interaction(.data[[pred1]], .data[[pred2]], sep = "_"), y = .data[[resp]], color = .data[[pred1]]))
    + geom_boxplot(outlier.alpha = 0, size = 1.1, fill = NA)
    + stat_summary(fun = mean, geom = "errorbar", aes(ymax = after_stat(y), ymin = after_stat(y)), width = 0.75, linewidth = 1.1, linetype = "dotted")
    + geom_jitter(mapping = aes(fill = .data[[pred1]]), shape = 23, color = "black", size = 3, width = 0.1, alpha = 0.9)
    + geom_errorbarh(
      data = p_data_contrasts, aes(xmin = paste(X1, .data[[pred2]], sep = "_"), xmax = paste(X2, .data[[pred2]], sep = "_"), y = pos.y), inherit.aes = FALSE,
      color = "black", height = 0.02 * amp, linewidth = 0.5
    )
    + geom_text(
      data = p_data_contrasts, aes(x = pos.x, y = pos.y, label = p.signif), inherit.aes = FALSE,
      size = 5, color = "black", fontface = "bold", vjust = 0, hjust = 0.5, position = position_nudge(y = 0.02 * amp)
    )
    ## Interactions
    + geom_errorbarh(
      data = p_data_interactions, aes(xmin = x1, xmax = x2, y = pos.y), inherit.aes = FALSE,
      color = "black", height = 0.02 * amp, linewidth = 0.5
    )
    + geom_text(
      data = p_data_interactions, aes(x = pos.x, y = pos.y, label = p.signif), inherit.aes = FALSE,
      size = 5, color = "black", fontface = "bold", vjust = 0, hjust = 0.5, position = position_nudge(y = 0.02 * amp)
    )
    + theme_minimal()
    + theme(legend.position = "none")
    + labs(x = str_c(pred1, " * ", pred2))
  )
}

make_interaction_boxplot(mod, pred1 = "am", pred2 = "cyl", scale = "link", adjust = "tukey", adjust_inter = "sidak")
```

```{r}
test <- tibble(to_split = c('a11', 'i01', 'u10', 'e00', 'a01', 'o11', 'u01'))

test |> tidyr::separate_wider_position(to_split, c(a = 1, b = 1, c = 1))
```

