```{r}
source("../../src/setup.R", echo = FALSE)
```

<!------------------------------------------------------------------------------>
<!------------------------------------------------------------------------------>
# I. Data:
***

```{r}
(Vasc_data <- load_vasc_data())

Vasc_responses <- c("Volume",	"Network Length",	"Surface Area",	"Branchpoints",	"Endpoints",	"Number of Segments",	"Segment Partitioning",	"Mean Segment Radius",	"Mean Segment Length",	"Mean Segment Tortuosity",	"Mean Segment Volume",	"Mean Segment Surface Area"
)

Vasc_predictors <- c("Stage", "Level", "Mouse", "Cerebellar Area", "Cerebellar Volume")
```


<!------------------------------------------------------------------------------>
<!------------------------------------------------------------------------------>
# II. Volume
***

<!------------------------------------------------------------------------------>
## 1. Models
***

**Gaussian:**

<!------------------------------------------------------------------------------>
<!------------------------------------------------------------------------------>
# III. Network Length
***

<!------------------------------------------------------------------------------>
## 1. Models
***

**Gaussian:**

<!------------------------------------------------------------------------------>
<!------------------------------------------------------------------------------>
# IV. Surface Area
***

<!------------------------------------------------------------------------------>
## 1. Models
***

**Gaussian:**

<!------------------------------------------------------------------------------>
<!------------------------------------------------------------------------------>
# V. Branchpoints
***

<!------------------------------------------------------------------------------>
## 1. Models
***

**Gaussian:**

<!------------------------------------------------------------------------------>
<!------------------------------------------------------------------------------>
# VI. Endpoints
***

<!------------------------------------------------------------------------------>
## 1. Models
***

**Gaussian:**

<!------------------------------------------------------------------------------>
<!------------------------------------------------------------------------------>
# VII. Number of Segments
***

<!------------------------------------------------------------------------------>
## 1. Models
***

**Gaussian:**

<!------------------------------------------------------------------------------>
<!------------------------------------------------------------------------------>
# VIII. Segment Partitioning
***

<!------------------------------------------------------------------------------>
## 1. Models
***

**Gaussian:**

<!------------------------------------------------------------------------------>
<!------------------------------------------------------------------------------>
# IX. Mean Segment Radius
***

<!------------------------------------------------------------------------------>
## 1. Models
***

**Gaussian:**


