<!----------------------------------------------------------------------------->
<!----------------------------------------------------------------------------->
# I. Data

```{r}
local({
    tmp <- tempfile(fileext = ".R")
    knitr::purl("analysis/clearing.Rmd", output = tmp, quiet = TRUE)
    source(tmp, local = FALSE)
    invisible(NULL)
})
```

<!----------------------------------------------------------------------------->
<!----------------------------------------------------------------------------->
# II. Figures

```{r}
no_strip <- theme(strip.text = element_blank(), strip.background = element_blank())
```

<!----------------------------------------------------------------------------->
## Individual plots per Stage

```{r}
clearing_models <- list(
    volume = list(tot = mod_vol_gamma_tot, ds = mod_vol_gamma_ds),
    network_length = list(tot = mod_length_gamma_tot, ds = mod_length_gamma_ds),
    surface_area = list(tot = mod_area_gamma_tot, ds = mod_area_gamma_ds),
    segment_partitioning = list(tot = mod_seg_part_gamma_tot, ds = mod_seg_part_gamma_ds),
    mean_segment_radius = list(tot = mod_seg_rad_gamma_tot, ds = mod_seg_rad_gamma_ds),
    mean_segment_length = list(tot = mod_seg_length_gamma_tot, ds = mod_seg_length_gamma_ds),
    mean_segment_tortuosity = list(tot = mod_seg_tort_gamma_tot, ds = mod_seg_tort_gamma_ds),
    mean_segment_volume = list(tot = mod_seg_vol_gamma_tot, ds = mod_seg_vol_gamma_ds),
    mean_segment_surface_area = list(tot = mod_seg_area_gamma_tot, ds = mod_seg_area_gamma_ds),
    branchpoints = list(tot = mod_numbranch_nbinom_tot, ds = mod_numbranch_nbinom_ds),
    endpoints = list(tot = mod_numends_nbinom_tot, ds = mod_numends_nbinom_ds),
    number_of_segments = list(tot = mod_numseg_nbinom_tot, ds = mod_numseg_nbinom_ds)
)

stages <- c("P4", "P8", "P12", "P21")

purrr::walk(stages, function(stage) {
    print(stage)
    purrr::walk(
        clearing_responses,
        function(var) {
            print(var)
            mods <- clearing_models[[var]]

            p_tot <- make_signif_boxplot(
                mods$tot,
                xaxis = "condition",
                facet = "stage",
                ncol = 1,
                only_facets = stage
            ) +
                no_strip

            save_png(
                p_tot,
                filename = paste0("mod_", var, "_tot_", stage),
                subfolder = paste0("IHC/", stage),
                width = 6,
                height = 6,
                display = FALSE
            )

            p_ds <- make_signif_boxplot_inter(
                mods$ds,
                pred1 = "condition",
                pred2 = "level",
                facet = "stage",
                ncol = 1,
                only_signif = FALSE,
                only_facets = stage
            ) +
                no_strip

            save_png(
                p_ds,
                filename = paste0("mod_", var, "_ds_", stage),
                subfolder = paste0("IHC/", stage),
                width = 8,
                height = 6,
                display = FALSE
            )
        },
        .progress = TRUE
    )
})
```

<!----------------------------------------------------------------------------->
## Normoxy only distribution

```{r}
clearing_total_normoxia_sex <- clearing |>
    dplyr::filter(level == "Total", condition == "N") |>
    dplyr::left_join(dplyr::select(supplementary_data$animal_data, mouse, sex), by = join_by(mouse)) |>
    dplyr::relocate(sex, .after = mouse) |>
    dplyr::arrange(stage)
```

```{r}
purrr::walk(c("volume", "network_length", "branchpoints", "number_of_segments"), function(m) {
    make_cerv_normalized_plot(clearing_total_normoxia_sex, metric = m) |>
        save_png(filename = paste0(m, "_normlized_by_sex"), subfolder = "IHC/normoxia", width = 6, height = 6)
})
```

```{r}
combined_normalized_normoxia_plots <- purrr::map(
    c("volume", "network_length", "branchpoints", "number_of_segments"),
    \(m) make_cerv_normalized_plot(clearing_total_normoxia_sex, metric = m)
) |>
    patchwork::wrap_plots(ncol = 4) +
    plot_layout(guides = "collect") &
    theme(legend.position = "bottom")

save_png(
    combined_normalized_normoxia_plots,
    filename = "normoxia_normalized_by_sex",
    subfolder = "IHC/normoxia",
    width = 24,
    height = 6,
    display = FALSE
)
```

<!----------------------------------------------------------------------------->
## PCA biplots

```{r}
purrr::walk(
    unique(clearing$stage) |> as.character() |> stringr::str_sort(numeric = TRUE),
    function(stage) {
        make_pca_plot(clearing, stage = stage) |>
            save_png(
                filename = paste0("Biplot - ", stage),
                subfolder = "IHC/PCA",
                width = 8,
                height = 8,
                display = FALSE
            )
    },
    .progress = TRUE
)
```

<!----------------------------------------------------------------------------->
<!----------------------------------------------------------------------------->
# III. Supplementary

<!----------------------------------------------------------------------------->
## Figure 1: Total network (volume, length, area)

```{r}
tot_vol <- make_signif_boxplot(mod_vol_gamma_tot, xaxis = "condition", facet = "stage", ncol = 4)
tot_length <- make_signif_boxplot(mod_length_gamma_tot, xaxis = "condition", facet = "stage", ncol = 4)
tot_area <- make_signif_boxplot(mod_area_gamma_tot, xaxis = "condition", facet = "stage", ncol = 4)
```

```{r}
#| fig-height: 17
#| fig-width: 14
(tot_vol / (tot_length + no_strip) / (tot_area + no_strip) + plot_layout(axes = "collect")) |>
    save_png("Fig1", subfolder = "IHC", width = 14, height = 17)
```

<!----------------------------------------------------------------------------->
## Figure 2: Total network (topology & shape)

```{r}
tot_numseg <- make_signif_boxplot(mod_numseg_nbinom_tot, xaxis = "condition", facet = "stage", ncol = 4)
tot_numbranch <- make_signif_boxplot(mod_numbranch_nbinom_tot, xaxis = "condition", facet = "stage", ncol = 4)
tot_numends <- make_signif_boxplot(mod_numends_nbinom_tot, xaxis = "condition", facet = "stage", ncol = 4)
tot_seg_part <- make_signif_boxplot(mod_seg_part_gamma_tot, xaxis = "condition", facet = "stage", ncol = 4)
tot_seg_tort <- make_signif_boxplot(mod_seg_tort_gamma_tot, xaxis = "condition", facet = "stage", ncol = 4)
```

```{r}
#| fig-height: 20
#| fig-width: 14
(tot_numseg /
    (tot_numbranch + no_strip) /
    (tot_numends + no_strip) /
    (tot_seg_part + no_strip) /
    (tot_seg_tort + no_strip) +
    plot_layout(axes = "collect")) |>
    save_png("Fig2", subfolder = "IHC", width = 14, height = 20)
```

<!----------------------------------------------------------------------------->
## Figure 3: Total segment averages

```{r}
tot_seg_vol <- make_signif_boxplot(mod_seg_vol_gamma_tot, xaxis = "condition", facet = "stage", ncol = 4)
tot_seg_area <- make_signif_boxplot(mod_seg_area_gamma_tot, xaxis = "condition", facet = "stage", ncol = 4)
tot_seg_length <- make_signif_boxplot(mod_seg_length_gamma_tot, xaxis = "condition", facet = "stage", ncol = 4)
tot_seg_rad <- make_signif_boxplot(mod_seg_rad_gamma_tot, xaxis = "condition", facet = "stage", ncol = 4)
```

```{r}
#| fig-height: 20
#| fig-width: 14
(tot_seg_vol /
    (tot_seg_area + no_strip) /
    (tot_seg_length + no_strip) /
    (tot_seg_rad + no_strip) +
    plot_layout(axes = "collect")) |>
    save_png("Fig3", subfolder = "IHC", width = 14, height = 20)
```

<!----------------------------------------------------------------------------->
## Figure 4

```{r}
ds_vol <- make_signif_boxplot_inter(mod_vol_gamma_ds, pred1 = "condition", pred2 = "level", facet = "stage", ncol = 4)
ds_length <- make_signif_boxplot_inter(
    mod_length_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 4
)
ds_numbranch <- make_signif_boxplot_inter(
    mod_numbranch_nbinom_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 4
)
ds_seg_tort <- make_signif_boxplot_inter(
    mod_seg_tort_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 4
)
ds_seg_part <- make_signif_boxplot_inter(
    mod_seg_part_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 4
)
ds_seg_vol <- make_signif_boxplot_inter(
    mod_seg_vol_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 4
)
ds_seg_area <- make_signif_boxplot_inter(
    mod_seg_area_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 4
)
```

```{r}
#| fig-height: 28
#| fig-width: 17
(ds_vol /
    (ds_length + no_strip) /
    (ds_numbranch + no_strip) /
    (ds_seg_tort + no_strip) /
    (ds_seg_part + no_strip) /
    (ds_seg_vol + no_strip) /
    (ds_seg_area + no_strip) +
    plot_layout(axes = "collect")) |>
    save_png("Fig4", subfolder = "IHC", width = 17, height = 28)
```

<!----------------------------------------------------------------------------->
## Figure 5

```{r}
ds_area <- make_signif_boxplot_inter(mod_area_gamma_ds, pred1 = "condition", pred2 = "level", facet = "stage", ncol = 4)
```

```{r}
#| fig-height: 20
#| fig-width: 18
(ds_vol / (ds_length + no_strip) / (ds_area + no_strip) + plot_layout(axes = "collect")) |>
    save_png("Fig5", subfolder = "IHC", width = 18, height = 20)
```

<!----------------------------------------------------------------------------->
## Figure 6

```{r}
ds_numseg <- make_signif_boxplot_inter(
    mod_numseg_nbinom_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 4
)
ds_numends <- make_signif_boxplot_inter(
    mod_numends_nbinom_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 4
)
```

```{r}
#| fig-height: 25
#| fig-width: 18
(ds_numseg /
    (ds_numbranch + no_strip) /
    (ds_numends + no_strip) /
    (ds_seg_part + no_strip) /
    (ds_seg_tort + no_strip) +
    plot_layout(axes = "collect")) |>
    save_png("Fig6", subfolder = "IHC", width = 18, height = 25)
```

<!----------------------------------------------------------------------------->
## Figure 7

```{r}
ds_seg_length <- make_signif_boxplot_inter(
    mod_seg_length_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 4
)
ds_seg_rad <- make_signif_boxplot_inter(
    mod_seg_rad_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 4
)
```

```{r}
#| fig-height: 22
#| fig-width: 18
(ds_seg_vol /
    (ds_seg_area + no_strip) /
    (ds_seg_length + no_strip) /
    (ds_seg_rad + no_strip) +
    plot_layout(axes = "collect")) |>
    save_png("Fig7", subfolder = "IHC", width = 18, height = 22)
```

<!----------------------------------------------------------------------------->
## Figure 8

```{r}
ds_vol_P4 <- make_signif_boxplot_inter(
    mod_vol_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P4"
)

ds_seg_part_P8 <- make_signif_boxplot_inter(
    mod_seg_part_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P8"
)

ds_area_P12 <- make_signif_boxplot_inter(
    mod_area_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P12"
)

ds_numends_P21 <- make_signif_boxplot_inter(
    mod_numends_nbinom_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P21"
)

ds_length_P4 <- make_signif_boxplot_inter(
    mod_length_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P4"
)

ds_endpoints_P8 <- make_signif_boxplot_inter(
    mod_numends_nbinom_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P8"
)

ds_length_P12 <- make_signif_boxplot_inter(
    mod_length_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P12"
)

ds_seg_part_P4 <- make_signif_boxplot_inter(
    mod_seg_part_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P4"
)

ds_seg_part_P12 <- make_signif_boxplot_inter(
    mod_seg_part_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P12"
)

ds_numbranch_P4 <- make_signif_boxplot_inter(
    mod_numbranch_nbinom_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P4"
)

ds_numseg_P4 <- make_signif_boxplot_inter(
    mod_numseg_nbinom_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P4"
)
```

```{r}
#| fig-height: 30
#| fig-width: 20
layout <- "
ABCD
EGH#
I#J#
K###
L###
"

fig8 <- ds_vol_P4 +
    ds_seg_part_P8 +
    ds_area_P12 +
    ds_numends_P21 +
    ds_length_P4 +
    ds_endpoints_P8 +
    ds_length_P12 +
    ds_seg_part_P4 +
    ds_seg_part_P12 +
    ds_numbranch_P4 +
    ds_numseg_P4 +
    plot_layout(design = layout, guides = "collect", axis_titles = "collect", axes = "collect")

save_png(fig8, filename = "Fig8", subfolder = "IHC", width = 20, height = 30)
```

<!----------------------------------------------------------------------------->
## Figure 9

```{r}
ds_seg_length_P4 <- make_signif_boxplot_inter(
    mod_seg_length_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P4"
)

ds_seg_length_P8 <- make_signif_boxplot_inter(
    mod_seg_length_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P8"
)

ds_seg_area_P4 <- make_signif_boxplot_inter(
    mod_seg_area_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P4"
)

ds_seg_area_P8 <- make_signif_boxplot_inter(
    mod_seg_area_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P8"
)

ds_seg_rad_P4 <- make_signif_boxplot_inter(
    mod_seg_rad_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P4"
)

ds_seg_tort_P4 <- make_signif_boxplot_inter(
    mod_seg_tort_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P4"
)

ds_seg_tort_P21 <- make_signif_boxplot_inter(
    mod_seg_tort_gamma_ds,
    pred1 = "condition",
    pred2 = "level",
    facet = "stage",
    ncol = 1,
    only_signif = FALSE,
    only_facets = "P21"
)
```

```{r}
#| fig-height: 24
#| fig-width: 15
layout <- "
ABC
DE#
G##
H##
"

fig9 <- ds_seg_length_P4 +
    ds_seg_length_P8 +
    ds_seg_tort_P21 +
    ds_seg_area_P4 +
    ds_seg_area_P8 +
    ds_seg_rad_P4 +
    ds_seg_tort_P4 +
    plot_layout(design = layout, guides = "collect", axis_titles = "collect", axes = "collect")

save_png(fig9, filename = "Fig9", subfolder = "IHC", width = 15, height = 24)
```
